import { Injectable, Logger } from '@nestjs/common';
import { MailService } from '../../mail/mail.service.js';
import { Severity } from '../entities/monitoring-report.entity.js';

@Injectable()
export class AlertsService {
  private readonly logger = new Logger(AlertsService.name);

  constructor(private mailService: MailService) {}

  /**
   * Triggers an alert based on the report's severity and frequency.
   */
  async triggerAlert(report: any) {
    if (report.severity === Severity.HIGH || report.frequency > 20) {
      this.logger.warn(`🚨 HIGH SEVERITY ALERT: ${report.errorType}`);
      
      const adminEmail = process.env.ADMIN_EMAIL || 'admin@jobito.com';
      const subject = `[Jobito Monitoring] HIGH SEVERITY: ${report.errorType}`;
      
      const htmlContent = `
        <div style="font-family: Arial, sans-serif; border: 2px solid #e11d48; padding: 20px; border-radius: 8px;">
          <h2 style="color: #e11d48;">🚨 System Security Alert</h2>
          <p><strong>Error Type:</strong> ${report.errorType}</p>
          <p><strong>Severity:</strong> <span style="background: #e11d48; color: white; padding: 2px 5px; border-radius: 4px;">${report.severity}</span></p>
          <p><strong>Frequency:</strong> ${report.frequency} occurrences</p>
          <hr/>
          <p><strong>Description:</strong> ${report.description}</p>
          <p><strong>Suggested Solution:</strong> <br/> ${report.suggestedSolution}</p>
          <hr/>
          <p style="font-size: 12px; color: #666;">Generated by Jobito Smart Monitoring System</p>
        </div>
      `;

      try {
        await this.mailService.sendSystemAlert(adminEmail, subject, htmlContent);
        this.logger.log(`Alert email sent to ${adminEmail}`);
      } catch (err) {
        this.logger.error(`Failed to send alert email: ${err.message}`);
      }
    }
  }
}
